version: '2.4'
services:

  generator:
    container_name: generator
    environment:
      - SPRING_CONFIG_LOCATION=file:/application.properties
    image: menski/zeebe-test-data-generator:latest
    ports:
      - 9090:9090
    restart: always
    volumes:
      - ./config/generator.properties:/application.properties

  operate:
    container_name: operate
    environment:
      - SPRING_PROFILES_ACTIVE=dev,dev-data
      - JAVA_OPTS=-Dlogging.config=file:/usr/app/config/log4j2.xml
      - SPRING_CONFIG_LOCATION=file:/usr/app/config/application.yml
    image: camunda/operate:1.1.0-alpha1
    ports:
      - 8080:8080
    restart: always
    volumes:
      - ./config/application.yml:/usr/app/config/application.yml
      - ./config/log4j2.xml:/usr/app/config/log4j2.xml

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - processors=1
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    restart: always

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.8.2
    ports:
        - 5601:5601
    links:
        - elasticsearch

  zeebe:
    container_name: zeebe
    image: camunda/zeebe:0.21.0-alpha1
    environment:
      - "JAVA_TOOL_OPTIONS=-Xms512m -Xmx512m"
      - ZEEBE_HOST=${ZEEBE_HOST:-}
      - ZEEBE_PARTITIONS_COUNT=2
      #- "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n"
    ports:
      - 26501:26501
      - 26500:26500
      - 8000:8000
    restart: always
    volumes:
      - ./config/zeebe.cfg.toml:/usr/local/zeebe/conf/zeebe.cfg.toml


