[[exporters]]
id = "debug"
className = "io.zeebe.broker.exporter.debug.DebugHttpExporter"
  [exporters.args]
  limit = 3000

[[exporters]]
id = "elasticsearch"
className = "io.zeebe.exporter.ElasticsearchExporter"

  [exporters.args]
  url = "http://elasticsearch:9200"

  [exporter.args.bulk]
   size = 1

